# Generated by Django 6.1.1 on 2026-10-05 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(default='Queued for processing', max_length=255)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('aoi_geojson', models.TextField(help_text='User selected AOI geometry in GeoJSON format')),
                ('flood_date', models.DateField(db_index=True)),
                ('use_segmentation', models.BooleanField(default=True, help_text='Run U-Net flood segmentation model')),
                ('trace_flood_path', models.BooleanField(default=False, help_text='Trace flood path downstream using DEM')),
                ('source_point_lon', models.FloatField(blank=True, null=True)),
                ('source_point_lat', models.FloatField(blank=True, null=True)),
                ('sentinel1_pre_path', models.CharField(blank=True, default='', max_length=500)),
                ('sentinel1_post_path', models.CharField(blank=True, default='', max_length=500)),
                ('sentinel2_path', models.CharField(blank=True, default='', max_length=500)),
                ('dem_path', models.CharField(blank=True, default='', max_length=500)),
                ('flood_area_km2', models.FloatField(blank=True, null=True)),
                ('buildings_affected', models.IntegerField(blank=True, null=True)),
                ('buildings_possibly_affected', models.IntegerField(blank=True, null=True)),
                ('roads_damaged_km', models.FloatField(blank=True, null=True)),
                ('bridges_damaged', models.IntegerField(blank=True, null=True)),
                ('settlements_cutoff', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodExtent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geojson_path', models.CharField(max_length=500)),
                ('geotiff_path', models.CharField(blank=True, default='', max_length=500)),
                ('confidence_score', models.FloatField(default=0.85)),
                ('source', models.CharField(default='fused', help_text="'sar_only', 'optical_only', or 'fused'", max_length=50)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flood_extent', to='analysis.analysisjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloodPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_point_geojson', models.TextField()),
                ('path_geojson', models.TextField(help_text='LineString of the flow path')),
                ('settlements_on_path', models.TextField(default='[]', help_text='JSON list of settlements along the path')),
                ('path_length_km', models.FloatField(default=0.0)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flood_path', to='analysis.analysisjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SituationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_english', models.TextField()),
                ('report_nepali', models.TextField(default='')),
                ('stats_snapshot', models.TextField(help_text='JSON snapshot of stats used for LLM generation')),
                ('llm_model', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=500)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='situation_report', to='analysis.analysisjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CutoffSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('geometry_geojson', models.TextField(help_text='Point geometry in GeoJSON format')),
                ('is_cutoff', models.BooleanField(db_index=True, default=True)),
                ('nearest_hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_hospital_geojson', models.TextField(blank=True, null=True)),
                ('pre_flood_distance_km', models.FloatField(blank=True, null=True)),
                ('population_estimate', models.IntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_settlements', to='analysis.analysisjob')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'is_cutoff'], name='analysis_cu_job_id_6c84c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DamagedFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('osm_id', models.CharField(max_length=100)),
                ('osm_type', models.CharField(help_text="'building', 'road', or 'bridge'", max_length=50)),
                ('osm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('affected', 'Affected'), ('possibly_affected', 'Possibly Affected'), ('not_affected', 'Not Affected')], db_index=True, default='affected', max_length=30)),
                ('overlap_pct', models.FloatField(default=0.0)),
                ('geometry_geojson', models.TextField(help_text='Feature geometry in GeoJSON format')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_features', to='analysis.analysisjob')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'status'], name='analysis_da_job_id_c50458_idx'), models.Index(fields=['job', 'osm_type'], name='analysis_da_job_id_52e89c_idx')],
            },
        ),
    ]
