# Generated by Django 6.1.1 on 2026-10-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodpath',
            name='avg_speed_kmh',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='floodpath',
            name='elevation_drop_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floodpath',
            name='end_elevation_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floodpath',
            name='settlement_etas',
            field=models.TextField(default='[]', help_text='JSON list of settlements with arrival timeline'),
        ),
        migrations.AddField(
            model_name='floodpath',
            name='start_elevation_m',
            field=models.IntegerField(default=0),
        ),
    ]
